Fix undefined local variable error output directory is not created
It is reproducible by fluent-diagtool -t fluentd -o nonexistent:

  NameError: undefined local variable or method `basedir' for #<Diagtool::DiagUtils:0x00007f8dc3f75820 @time_format="20230822122658">

            raise "output directory '#{basedir}' does not exist"
                                       ^^^^^^^
  /work/fluent/fluentd/fluent-diagtool/lib/fluent/diagtool/diagutils.rb:232:in `parse_diagconf'
  /work/fluent/fluentd/fluent-diagtool/lib/fluent/diagtool/diagutils.rb:29:in `initialize'
  /work/fluent/fluentd/fluent-diagtool/exe/fluent-diagtool:40:in `new'
  /work/fluent/fluentd/fluent-diagtool/exe/fluent-diagtool:40:in `<top (required)>'

Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>